apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: boardgame-web-deploy
  labels:
    app: boardgame-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame-web
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: boardgame-web
        tier: frontend
    spec:
      containers:
      - name: boardgame-web
        image: ceemeese/boardgame-web-v2:00
        ports:
        - containerPort: 1234
        env:
        - name: API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: web-config
              key: API_BASE_URL
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: web-config
              key: APP_ENV
